### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by jywarren** [bluemir/fisheye-correction-webgl#1]
Hello! I've been doing some work based on your library, and wanted to ask if you'd attach an open source license to your work, so I can contribute mine under the same license. MIT or GPLv3, maybe?

I built on your initial code to make an online interface for adjusting images:

https://jywarren.github.io/fisheyegl/example/

https://github.com/jywarren/fisheyegl

I'd be happy to rebase and merge my changes back into your repository if you'd prefer, but I want to release it as a Node.js and Bower package, so I wanted a shorter name.

**Comment by AlexVestin** [comment]
ping @bluemir awesome library! but would be it be possible to add a license to the code?

**Comment by bluemir** [comment]
Sorry for late reply.
I add 'LICENSE' file in  f36e3e815fa6e362dd16a888b9b806ef4745aa1a commit.

**Comment by jywarren** [comment]
Amazing, thank you!!!
